services:
  vault1:
    image: hashicorp/vault:1.21
    container_name: vault1
    hostname: vault1
    command: server
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault1/config.hcl:/vault/config/config.hcl
      - ./vault1/data:/vault/data
    ports:
      - "8200:8200"
    networks:
      - vault-net

  vault2:
    image: hashicorp/vault:1.21
    container_name: vault2
    hostname: vault2
    command: server
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault2/config.hcl:/vault/config/config.hcl
      - ./vault2/data:/vault/data
    ports:
      - "8201:8200"
    networks:
      - vault-net

  vault3:
    image: hashicorp/vault:1.21
    container_name: vault3
    hostname: vault3
    command: server
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault3/config.hcl:/vault/config/config.hcl
      - ./vault3/data:/vault/data
    ports:
      - "8202:8200"
    networks:
      - vault-net

networks:
  vault-net:
    driver: bridge
